### PR TITLE
Fixed IndexOperations.getIndexTemplate() logic

### LINKED ISSUE #416: [BUG] Unable to parse index template data
### What is the bug?
error when execute `GET /_index_template/<index template>` request, response can't be parsed

```
java.lang.StringIndexOutOfBoundsException: Range [-1, 68) out of bounds for length 68
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[na:na]
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[na:na]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[na:na]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[na:na]
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2834) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2807) ~[na:na]
	at org.opensearch.data.client.osc.TypeUtils.removePrefixFromJson(TypeUtils.java:475) ~[spring-data-opensearch-1.6.1.jar:na]
	at org.opensearch.data.client.osc.TypeUtils.typeMapping(TypeUtils.java:471) ~[spring-data-opensearch-1.6.1.jar:na]
	at org.opensearch.data.client.osc.ResponseConverter.indexGetComponentTemplateData(ResponseConverter.java:329) ~[spring-data-opensearch-1.6.1.jar:na]
	at org.opensearch.data.client.osc.ResponseConverter.indexGetComponentTemplate(ResponseConverter.java:323) ~[spring-data-opensearch-1.6.1.jar:na]
	at org.opensearch.data.client.osc.ResponseConverter.lambda$getIndexTemplates$10(ResponseConverter.java:310) ~[spring-data-opensearch-1.6.1.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[na:na]
	at org.opensearch.data.client.osc.ResponseConverter.getIndexTemplates(ResponseConverter.java:309) ~[spring-data-opensearch-1.6.1.jar:na]
	at org.opensearch.data.client.osc.IndicesTemplate.getIndexTemplate(IndicesTemplate.java:369) ~[spring-data-opensearch-1.6.1.jar:na]
	at org.springframework.data.elasticsearch.core.IndexOperations.getIndexTemplate(IndexOperations.java:347) ~[spring-data-elasticsearch-5.4.2.jar:5.4.2]
```

The problem in the code
```
    @Nullable
    static Document typeMapping(@Nullable TypeMapping typeMapping) {
        return (typeMapping != null) ? Document.parse(removePrefixFromJson(typeMapping.toString())) : null;
    }
```
`TypeMapping` doesn't overwrite `toString()` method and this method returns something like `org.opensearch.client.opensearch._types.mapping.TypeMapping@24afa506`

To resolve this problem need to change the implementation of `TypeMapping.toString()` or use `TypeMapping.toJsonString()` (in this case `removePrefixFromJson()` can be removed)

### How can one reproduce the bug?
execute `GET /_index_template/<index template>` for index template which contains a mapping

### What is the expected behavior?
response from server should be read w/o errors

### PR DESCRIPTION
**Pull request by pstetsuk**
Fixed #416

### CODE REVIEW

File: spring-data-opensearch/src/test/java/org/opensearch/data/client/core/indices/IndexTemplateOperationsOSCIntegrationTests.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+@SpringIntegrationTest
+@ContextConfiguration(classes = {IndexTemplateOperationsOSCIntegrationTests.Config.class})
+public class IndexTemplateOperationsOSCIntegrationTests {
+
+    @Configuration
+    @Import({OpenSearchTemplateConfiguration.class})
+    static class Config {
+        @Bean
+        IndexNameProvider indexNameProvider() {
+            return new IndexNameProvider("indextemplateoperations-es7");
```
Comment (reta) [inline spring-data-opensearch/src/test/java/org/opensearch/data/client/core/indices/IndexTemplateOperationsOSCIntegrationTests.java:45]:
```suggestion
            return new IndexNameProvider("indextemplateoperations-os");
```

**Comment by reta** [comment]
Thank you @pstetsuk !

**Review by reta — APPROVED** [review]
